### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dfontana** [dfontana/keeper#1]
# Keeper's Todo List

This ticket serves as the TODO list for keeper. Eventually each ask should be its own issue, but for now we'll stick with the quick n' dirty
- General
  - [x] Missing ~/.keeper throws an error 😄 Should generate if missing!
- List
  - [ ] Add single directory flag functionality
  - [ ] Add support for multiple directory flags
  - [ ] Can we get colorized `grep` output printing again? :(
- Del
  - [x] Providing no arguments should print `help`
  - [x] When branch exists local || remote (not both), prevent error causing command to bail
  - [ ] Add single directory flag functionality
  - [ ] Add a `--force` to override the confirmation prompt (maybe? This command can be dangerous...)
- Each
  - [ ] Rename to run
  - [ ] Implement
- Start
  - [ ] Implement for current directory
  - [ ] Implement for given directory flags
  - [ ] Add config templating
  - [ ] Directory specific templates?###

**Comment by dfontana** [comment]
Broken into several other issues for easier digesting: #4 #5 #6 #7 #8 #9 #10
